### PR TITLE
Add annotation delete functionality

### PR DESCRIPTION
**Pull request by Vaspra**
This also fixes some changes from the prior PR for uploading annotations (incorrectly).

### CODE REVIEW

**Review by exhaustedbrit — APPROVED** [review]
Looks good, just some lint errors

**Comment by ahaith** [comment]
@Vaspra I presume you're developing in Spyder. Looks like it's possible to turn on linting in the editor: https://stackoverflow.com/questions/51463223/how-to-use-pep8-module-using-spyder
Having this is a godsend as you can just keep it compliant as you code.

**Comment by Vaspra** [comment]
They are "linting" errors but I would argue that the rules are detracting from easily readable format. Could we review the linting rules? IMO properties, docstrings and linespacing between functions need changing.

**Comment by ahaith** [comment]
Sure, we can definitely review the rules. I'm no purist on this stuff, but a few points in their favour:
- It's good to stay consistent across our codebases
- A lot of other orgs & codebases follow these standard rules
- Once you're used to different line spacing, it's just as easy to read!

That said I would rather have linting green, but with a few rules disabled.
See the .flake8 file, and feel free to add a few to the ignore list - we can always re-add some later if we can agree on e.g. line spacing.

**Pull request merged**
